---
- name: Creating a file
  hosts: test
  tasks: 
    - name: using server to create file on host    
      file:  
        path: /home/ubuntu/File_module.txt  
        state: touch
    - name: creating a direcory if it doesn't exist
      file:
        path: /home/ubuntu/my_dir
        state: directory
    - name: removing a directory
      file:
        path: /home/ubuntu/dir1
        state: absent
     
...
